name: build plugin

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '要构建的 tag'
        required: true
        default: ''
        
env:
  DOTNET_VERSION: '8.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout 指定 tag，如果为空就用默认 branch
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag || 'master' }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish plugin (with cipx package)
      run: dotnet publish -c Release -p:CreateCipx=true

    - name: Upload cipx artifact
      uses: actions/upload-artifact@v4
      with:
        name: EasyNotification-plugin
        path: EasyNotification/cipx/EasyNotification.cipx
        retention-days: 7

    - name: Upload checksums
      uses: actions/upload-artifact@v4
      with:
        name: EasyNotification-checksums
        path: EasyNotification/cipx/checksums.md
        retention-days: 7
